### ISSUE TITLE
Webhook URI not ready

### ISSUE THREAD

**Issue by kshanovskyi** [aliencube/microsoft-teams-actions#5]
Hi, after adding this action to pipeline I am always getting such an error:

`Time Elapsed 00:00:02.25
Unhandled exception. System.AggregateException: One or more errors occurred. (Webhook URI not ready)
 ---> System.InvalidOperationException: Webhook URI not ready
   at Aliencube.GitHubActions.Teams.ConsoleApp.MessageHandler.SendMessageAsync(HttpClient client) in /app/src/GitHubActions.Teams.ConsoleApp/MessageHandler.cs:line 66
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Aliencube.GitHubActions.Teams.ConsoleApp.Program.OnParsed(Options options) in /app/src/GitHubActions.Teams.ConsoleApp/Program.cs:line 56
   at Aliencube.GitHubActions.Teams.ConsoleApp.Program.<>c.<Main>b__11_1(Options options) in /app/src/GitHubActions.Teams.ConsoleApp/Program.cs:line 47
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Aliencube.GitHubActions.Teams.ConsoleApp.Program.Main(String[] args) in /app/src/GitHubActions.Teams.ConsoleApp/Program.cs:line 46`

**Comment by shrabas** [comment]
Got same issue. any plans to fix this?

**Comment by insearching** [comment]
> Hi, after adding this action to pipeline I am always getting such an error:
> 
> `Time Elapsed 00:00:02.25 Unhandled exception. System.AggregateException: One or more errors occurred. (Webhook URI not ready) ---> System.InvalidOperationException: Webhook URI not ready at Aliencube.GitHubActions.Teams.ConsoleApp.MessageHandler.SendMessageAsync(HttpClient client) in /app/src/GitHubActions.Teams.ConsoleApp/MessageHandler.cs:line 66 --- End of inner exception stack trace --- at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
> at System.Threading.Tasks.Task`1.get_Result() at Aliencube.GitHubActions.Teams.ConsoleApp.Program.OnParsed(Options options) in /app/src/GitHubActions.Teams.ConsoleApp/Program.cs:line 56 at Aliencube.GitHubActions.Teams.ConsoleApp.Program.<>c.<Main>b__11_1(Options options) in /app/src/GitHubActions.Teams.ConsoleApp/Program.cs:line 47 at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
> at Aliencube.GitHubActions.Teams.ConsoleApp.Program.Main(String[] args) in /app/src/GitHubActions.Teams.ConsoleApp/Program.cs:line 46`

 Documentation here https://github.com/marketplace/actions/microsoft-teams-generic is wrong, you should use webhook_uri instead.

**Comment by justinyoo** [comment]
@shrabas @insearching OMG Thanks for pointing this out! It's typo. Should have been `webhook_uri`.

**Comment by justinyoo** [comment]
Thanks @insearching for your PR #6 and #8 Both have been merged.

**Comment by PMLP-novo** [comment]
Been here trice because I on two different projects have misspelled parameters :) Issues like this brings so much value
